spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 50MB   # uploaded_file_size default 1MB max 10MB
      max-request-size: 50MB
    tomcat:
      max-swallow-size: 100MB #最大吞吐量为-1

  mvc:
    static-path-pattern: any-pattern




mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # running log
    map-underscore-to-camel-case: true  # Mapping: phone_number => phoneNumber

  global-config:
    db-config:
      id-type: ASSIGN_ID   # snow_flake auto_increment
